---

sudo: required

dist: trusty

language: python

python:
  - 2.7

services:
  - docker

env:
  global:
    - ANSIBLE_FORCE_COLOR: true
    - ANSIBLE_LOG_PATH: './ansible.log'
    - ANSIBLE_ROLES_PATH: '../'

before_install:
  - pip install --upgrade git+git://github.com/ansible/ansible.git@stable-2.4
  - pip install --upgrade 'docker >=2.4.0,<3.0'
  - pip install --upgrade 'docker-compose <1.19.0'
  - pip install --upgrade git+git://github.com/ansible/ansible-container.git@develop

install:
  - pip install -r ansible-requirements.txt
  - ansible-galaxy install -r requirements.yml

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker version
  - docker-compose version
  - docker info
  - yamllint -c .yamllint .
  - ansible-container build --use-local-python -- --diff
  - ansible-container run
  - docker ps -a
  - docker image list
  - ansible-playbook -i localhost, -c local tests/test.yml --syntax-check
  - ansible-playbook -i localhost, -c local tests/test.yml --diff
  - ansible-playbook -i localhost, -c local tests/test.yml --diff
  - tail -n 1 $ANSIBLE_LOG_PATH | grep -Eq 'changed=0 +unreachable=0 +failed=0'
  - ansible-container stop --force

after_success:
  - |
    if [[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      read -a v <<< $(echo ${TRAVIS_TAG} | sed 's/[\.\-]/ /g')
      ansible-container push --push-to docker --tag $TRAVIS_TAG
      ansible-container push --push-to docker --tag ${v[0]}.${v[1]}.${v[2]}
      ansible-container push --push-to docker --tag ${v[0]}.${v[1]}
      ansible-container push --push-to docker --tag ${v[0]}
      ansible-container push --push-to docker --tag latest
    fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
